apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: javapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Adjust this value based on your application's needs
