version: "3.8"

services:
  postgres_user:
    image: postgres:latest
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Quantum9963
      POSTGRES_DB: user_db
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  postgres_product:
    image: postgres:latest
    container_name: postgres_product_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Quantum9963
      POSTGRES_DB: product_db
    volumes:
      - postgres-product-data:/var/lib/postgresql/data

  user-service:
    build: ./path/to/your/user-service
    container_name: user-service
    depends_on:
      - postgres_user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_user:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Quantum9963
    ports:
      - "8080:8080"

  product-service:
    build: ./path/to/your/product-service
    container_name: product-service
    depends_on:
      - postgres_product
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_product:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Quantum9963
    ports:
      - "8081:8081"

volumes:
  postgres-user-data:
  postgres-product-data:
